---
- name: Perform conditional test
  hosts: all
  tasks:
    - name: Install vsftpd if sufficient space on `/boot`
      yum:
        name: vsftpd
        state: latest
      loop: "{{ ansible_mounts }}"
      when: item.mount == '/boot' and item.size_available > 100000
