---
- name: Demonstrate file copy modules
  hosts: all
  tasks:
    - name: Copy file to tmp
      copy:
        src: /etc/hosts
        dest: /tmp

    - name: Add some lines to /tmp/hosts
      blockinfile:
        path: /tmp/hosts
        block: |
          192.168.1.1 host1.example.com
          192.168.1.2 host2.example.com
        state: present

    - name: Get file checksum
      stat:
        path: /tmp/hosts
        checksum_algorithm: md5
      register: file_result

    - name: Verify file checksum
      debug:
        msg: "File checksum: {{ file_result.stat.checksum }}"

    - name: Fetch file
      fetch:
        src: /tmp/hosts
        dest: /tmp
