---
- name: Create user using a variable
  hosts: all
  vars_files:
    - vars/users
  tasks:
    - name: Using `debug` to view the variable
      debug:
        msg: User is {{ user }}
    - name: Create a {{ user }} user
      user:
        name: "{{ user }}"
