---
- name: deploy vsftpd on ansible1
  hosts: ansible1
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
    - name: start vsftpd
      service:
        name: vsftpd
        enabled: true
    - name: create readme
      copy:
        content: "Welcome to Ansible1 host"
        dest: /var/ftp/pub/README
