---
- name: Install nginx on ansible1 using role
  hosts: ansible1
  pre_tasks:
    - name: Ensure httpd is removed so it don't conflict with nginx
      service:
        name: httpd
        state: stopped
  roles:
    - role: geerlingguy.nginx
