---
- name: Setup FTP server
  hosts: localhost
  tasks:
    - name: Install vsftpd
      yum:
        name: vsftpd
        state: latest

    - name: Enable vsftpd
      service:
        name: vsftpd
        state: started
        enabled: yes

    - name: Allow ftp traffic
      firewalld:
        service: ftp
        state: enabled
        permanent: yes
        immediate: yes

- name: Setup repository and share through FTP
  hosts: localhost
  tasks:
    - name: Download nmap and place it on FTP pub directory
      yum:
        name: nmap
        state: latest
        download_only: true
        download_dir: /var/ftp/repo

    - name: Index the directory as a repository
      command: createrepo /var/ftp/repo
